version: '3.8'
services:
    mongo-1-1:
        container_name: "mongo-1-1"
        image: ${TEST_MONGODB_IMAGE:-mongo:4.2}
        volumes:
            - ./docker/secret/keyfile:/data/keyfile
            - ./docker/secret/mongod.conf:/data/mongod.conf
        ports:
            - "${TEST_MONGODB_S1_PRIMARY_PORT:-17001}:27017"
        command: mongod --config /data/mongod.conf --replSet rs1 --shardsvr --port 27017  --oplogSize 16
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
        links:
            - mongo-1-2:mongo-1-2
            - mongo-1-3:mongo-1-3

    mongo-1-2:
        container_name: "mongo-1-2"
        image: ${TEST_MONGODB_IMAGE:-mongo:4.2}
        volumes:
            - ./docker/secret/keyfile:/data/keyfile
            - ./docker/secret/mongod.conf:/data/mongod.conf
        ports:
            - "${TEST_MONGODB_S1_SECONDARY1_PORT:-17002}:27017"
        command: mongod --config /data/mongod.conf --replSet rs1 --shardsvr --port 27017  --oplogSize 16
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root

    mongo-1-3:
        container_name: "mongo-1-3"
        image: ${TEST_MONGODB_IMAGE:-mongo:4.2}
        volumes:
            - ./docker/secret/keyfile:/data/keyfile
            - ./docker/secret/mongod.conf:/data/mongod.conf
        ports:
            - "${TEST_MONGODB_S1_SECONDARY2_PORT:-17003}:27017"
        command: mongod --config /data/mongod.conf --replSet rs1 --shardsvr --port 27017  --oplogSize 16
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root

    mongo-1-arbiter:
        container_name: "mongo-1-arbiter"
        volumes:
            - ./docker/secret/keyfile:/data/keyfile
            - ./docker/secret/mongod.conf:/data/mongod.conf
        image: ${TEST_MONGODB_IMAGE:-mongo:4.2}
        ports:
            - "${TEST_MONGODB_S1_ARBITER:-17011}:27017"
        command: mongod --config /data/mongod.conf --replSet rs1 --shardsvr --port 27017  --oplogSize 16
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root

    mongo-rs1-setup:
        container_name: "mongo-rs1-setup"
        image: ${TEST_MONGODB_IMAGE:-mongo:4.2}
        depends_on:
            - "mongo-1-1"
            - "mongo-1-2"
            - "mongo-1-3"
            - "mongo-1-arbiter"
        links:
            - mongo-1-1:mongo-1-1
            - mongo-1-2:mongo-1-2
            - mongo-1-3:mongo-1-3
            - mongo-1-arbiter:mongo-1-arbiter
        volumes:
            - ./docker/scripts:/scripts
        environment:
            - MONGO1=mongo-1-1
            - MONGO2=mongo-1-2
            - MONGO3=mongo-1-3
            - ARBITER=mongo-1-arbiter
            - RS=rs1
        entrypoint: [ "/scripts/setup.sh" ]
